/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package svna.templates;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import svna.Diagnostico;
import svna.Paciente;

/**
 *
 * @author gabri
 */
public class IMC extends javax.swing.JFrame {

    int id_usuario,cantidadP;
    String nombreD;
    boolean nota;
    Diagnostico diagnostico = new Diagnostico();
    float resultado;
    
    /**
     * Creates new form IMC
     */
    public IMC(int id) {
        initComponents();
        setLocationRelativeTo(null);
        id_usuario = id;
        nombreD = "IMC";
        nota = false;
        
        ArrayList<Paciente> pacientes = new ArrayList<Paciente>();
        pacientes = new Paciente().getAllPaciente();
        cantidadP = pacientes.size();
        
        pacientes = new Paciente().getAllPacienteIMC();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for(int i = 0; i<pacientes.size(); i++){
            model.addRow(new Object[]{pacientes.get(i).getId(),pacientes.get(i).getCedula(),pacientes.get(i).getNombres(),pacientes.get(i).getApellidos(), pacientes.get(i).getFechaN()});
        }
        
        pesoTxtF.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();

               // Verificar si la tecla pulsada no es un digito
               if(((caracter < '0') ||
                  (caracter > '9')) &&
                  (caracter != '.') &&
                  (caracter != '\b' /*corresponde a BACK_SPACE*/))
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });
        
        alturaTxtF.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();

               // Verificar si la tecla pulsada no es un digito
               if(((caracter < '0') ||
                  (caracter > '9')) &&
                  (caracter != '.') &&
                  (caracter != '\b' /*corresponde a BACK_SPACE*/))
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });
        
        diagnosticoTxt.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {  
                e.consume();  // ignorar el evento de teclado 
            }
         });
        
        kgMTxt.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {  
                e.consume();  // ignorar el evento de teclado 
            }
         });
        
        notasTxt.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {  
                if(!nota)
                    e.consume();  // ignorar el evento de teclado 
            }
         });
    }

    private IMC() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atrasBtn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atrasBtn3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        pesoTxtF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        alturaTxtF = new javax.swing.JFormattedTextField();
        calcularBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        diagnosticoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notasTxt = new javax.swing.JTextArea();
        kgMTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();

        atrasBtn2.setText("Atras");
        atrasBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtn2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Calcular IMC");

        atrasBtn3.setText("Atras");
        atrasBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtn3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cédula", "Nombres", "Apellidos", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("ID Paciente:");

        jLabel3.setText("Peso (Kg):");

        jLabel4.setText("Altura (M):");

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Diagnóstico:");

        jLabel6.setText("Notas:");

        notasTxt.setColumns(20);
        notasTxt.setRows(5);
        jScrollPane2.setViewportView(notasTxt);

        jLabel7.setText("Kg/m2");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diagnosticoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kgMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(atrasBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesoTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alturaTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calcularBtn)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(guardarBtn)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(pesoTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(alturaTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBtn))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(diagnosticoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(guardarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atrasBtn3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtn2ActionPerformed
        // TODO add your handling code here:

        MenuPrincipal menu = new MenuPrincipal(id_usuario);
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_atrasBtn2ActionPerformed

    private void atrasBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtn3ActionPerformed
        // TODO add your handling code here:

        MenuValoraciones menu = new MenuValoraciones(id_usuario);
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_atrasBtn3ActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
        
        if((int) idField.getValue() <= 0 || (int) idField.getValue() > cantidadP)
            flag = false;
        
        if(pesoTxtF.getText().isEmpty())
            flag = false;
        
        if(alturaTxtF.getText().isEmpty())
            flag = false;
        
        int posicion, contador = 0;
        
        //se busca la primera vez que aparece
        posicion = pesoTxtF.getText().indexOf('.');
        while (posicion != -1) { //mientras se encuentre el caracter
            contador++;           //se cuenta
            //se sigue buscando a partir de la posición siguiente a la encontrada                                 
            posicion = pesoTxtF.getText().indexOf('.', posicion + 1);
        }
        
        if(contador>1)
            flag = false;
        
        contador=0;
        
        //se busca la primera vez que aparece
        posicion = alturaTxtF.getText().indexOf('.');
        while (posicion != -1) { //mientras se encuentre el caracter
            contador++;           //se cuenta
            //se sigue buscando a partir de la posición siguiente a la encontrada                                 
            posicion = alturaTxtF.getText().indexOf('.', posicion + 1);
        }
        
        if(contador>1)
            flag = false;
        
        if(flag){
            
            
            diagnostico.setAltura(Float.parseFloat(alturaTxtF.getText()));
            diagnostico.setPeso(Float.parseFloat(pesoTxtF.getText()));
            diagnostico.setId_paciente((int) idField.getValue());
            resultado = diagnostico.calcularIMC();
            
            diagnosticoTxt.setText(diagnostico.diagnosticoIMC(resultado));
            DecimalFormat decimalFormat = new DecimalFormat("#.00");
            String res = decimalFormat.format(resultado);
            kgMTxt.setText(res);
            
            nota = true;
            
        }else{
            JOptionPane.showMessageDialog(null,"Por favor verificar la información ingresada");
        }
            
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
        
        boolean flag = true;
        
        if(diagnosticoTxt.getText().isEmpty())
            flag = false;
        
        if(flag){
            DecimalFormat decimalFormat = new DecimalFormat("#.00");
            String res = decimalFormat.format(resultado);
            
            diagnostico.setNotas(notasTxt.getText());
               
            diagnostico.registrarIMC(diagnosticoTxt.getText(), id_usuario, res, nombreD);
            
            MenuValoraciones menu = new MenuValoraciones(id_usuario);
            menu.setVisible(true);
            
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null,"Por favor verificar la información ingresada");
        }
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField alturaTxtF;
    private javax.swing.JButton atrasBtn2;
    private javax.swing.JButton atrasBtn3;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JTextField diagnosticoTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JSpinner idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kgMTxt;
    private javax.swing.JTextArea notasTxt;
    private javax.swing.JFormattedTextField pesoTxtF;
    // End of variables declaration//GEN-END:variables
}
