/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package svna.templates;

/**
 *
 * @author gabri
 */
public class MenuValoraciones extends javax.swing.JFrame {

    int id_usuario;
    
    /**
     * Creates new form MenuValoraciones
     */
    public MenuValoraciones(int id) {
        initComponents();
        setLocationRelativeTo(null);
        id_usuario = id;
    }

    private MenuValoraciones() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atrasBtn2 = new javax.swing.JButton();
        imcBtn = new javax.swing.JButton();
        pesoEdadBtn = new javax.swing.JButton();
        pesoTallaBtn = new javax.swing.JButton();
        pesoEmbarazoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menú Valoraciones");

        atrasBtn2.setText("Atras");
        atrasBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtn2ActionPerformed(evt);
            }
        });

        imcBtn.setText("Calcular IMC");
        imcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imcBtnActionPerformed(evt);
            }
        });

        pesoEdadBtn.setText("Calcular Peso/Edad");
        pesoEdadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoEdadBtnActionPerformed(evt);
            }
        });

        pesoTallaBtn.setText("Calcular Peso/Talla");
        pesoTallaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTallaBtnActionPerformed(evt);
            }
        });

        pesoEmbarazoBtn.setText("Calcular Ganancia de Peso (Embarazadas)");
        pesoEmbarazoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoEmbarazoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(atrasBtn2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesoTallaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesoEdadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesoEmbarazoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(imcBtn)
                .addGap(18, 18, 18)
                .addComponent(pesoEdadBtn)
                .addGap(18, 18, 18)
                .addComponent(pesoEmbarazoBtn)
                .addGap(18, 18, 18)
                .addComponent(pesoTallaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(atrasBtn2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtn2ActionPerformed
        // TODO add your handling code here:

        MenuPrincipal menu = new MenuPrincipal(id_usuario);
        menu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_atrasBtn2ActionPerformed

    private void imcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imcBtnActionPerformed
        // TODO add your handling code here:
        
        IMC imc = new IMC(id_usuario);
        imc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_imcBtnActionPerformed

    private void pesoEdadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoEdadBtnActionPerformed
        // TODO add your handling code here:
        PesoEdad pesoEdad = new PesoEdad(id_usuario);
        pesoEdad.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_pesoEdadBtnActionPerformed

    private void pesoTallaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTallaBtnActionPerformed
        // TODO add your handling code here:
        
        PesoTalla calcular = new PesoTalla(id_usuario);
        calcular.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_pesoTallaBtnActionPerformed

    private void pesoEmbarazoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoEmbarazoBtnActionPerformed
        // TODO add your handling code here:
        
        Embarazada embarazada = new Embarazada(id_usuario);
        embarazada.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_pesoEmbarazoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuValoraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuValoraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuValoraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuValoraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuValoraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn2;
    private javax.swing.JButton imcBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pesoEdadBtn;
    private javax.swing.JButton pesoEmbarazoBtn;
    private javax.swing.JButton pesoTallaBtn;
    // End of variables declaration//GEN-END:variables
}
