/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package svna.templates;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import svna.templates.MenuPrincipal;

/**
 *
 * @author gabri
 */
public class MenuPaciente extends javax.swing.JFrame {

    int id_usuario;
    /**
     * Creates new form MenuPaciente
     */
    public MenuPaciente(int id) {
        initComponents();
        setLocationRelativeTo(null);
        id_usuario = id;
    }

    private MenuPaciente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registrarMayorBtn = new javax.swing.JButton();
        consultarPacienteBtn = new javax.swing.JButton();
        consultarDiagnosticoBtn = new javax.swing.JButton();
        busquedaBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        registrarMenorBtn = new javax.swing.JButton();

        jButton6.setText("Registrar Paciente Mayor");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Historias y Registros de Pacientes");

        registrarMayorBtn.setText("Registrar Paciente Mayor");
        registrarMayorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMayorBtnActionPerformed(evt);
            }
        });

        consultarPacienteBtn.setText("Consultar Paciente");
        consultarPacienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPacienteBtnActionPerformed(evt);
            }
        });

        consultarDiagnosticoBtn.setText("Consultar Diagnóstico");
        consultarDiagnosticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDiagnosticoBtnActionPerformed(evt);
            }
        });

        busquedaBtn.setText("Busqueda Por Filtros");

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        registrarMenorBtn.setText("Registrar Paciente Menor");
        registrarMenorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMenorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrarMayorBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(registrarMenorBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(consultarDiagnosticoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultarPacienteBtn)))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(atrasBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(busquedaBtn)
                        .addGap(184, 184, 184))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarMayorBtn)
                    .addComponent(registrarMenorBtn))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consultarDiagnosticoBtn)
                    .addComponent(consultarPacienteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(busquedaBtn)
                .addGap(10, 10, 10)
                .addComponent(atrasBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarPacienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPacienteBtnActionPerformed
        // TODO add your handling code here:
        ConsultarPaciente consulta = new ConsultarPaciente(id_usuario);
        consulta.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_consultarPacienteBtnActionPerformed

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal menu = new MenuPrincipal(id_usuario);
        menu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void registrarMayorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMayorBtnActionPerformed
       // TODO add your handling code here:
            RegistrarPacienteMayor mayor = new RegistrarPacienteMayor(id_usuario);
            mayor.setVisible(true);
            
            this.dispose();
    }//GEN-LAST:event_registrarMayorBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void registrarMenorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMenorBtnActionPerformed
        // TODO add your handling code here:
            RegistrarPacienteMenor menor = new RegistrarPacienteMenor(id_usuario);
            menor.setVisible(true);
            
            this.dispose();
    }//GEN-LAST:event_registrarMenorBtnActionPerformed

    private void consultarDiagnosticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDiagnosticoBtnActionPerformed
        // TODO add your handling code here:
        ConsultarDiagnostico diagnostico = new ConsultarDiagnostico(id_usuario);
        diagnostico.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_consultarDiagnosticoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JButton busquedaBtn;
    private javax.swing.JButton consultarDiagnosticoBtn;
    private javax.swing.JButton consultarPacienteBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarMayorBtn;
    private javax.swing.JButton registrarMenorBtn;
    // End of variables declaration//GEN-END:variables
}
